import type { ComponentType } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  APAnalyticsV2,
  APAPIManagementPage,
  APAIModelV2,
  APAuditV2,
  APBackupPage,
  APBillingV2,
  APCMSPage,
  APClientsV2,
  APDashboardV2,
  APDatasetsV2,
  APHealthPage,
  APKnowledgeBasePage,
  APLawyersV2,
  APReportsV2,
  APRolesV2,
  APSecurityV2,
  APSettingsV2,
  APSupportPage,
  APUsersV2,
} from './AdminPortalPages'
import {
  CPDashboardPageV2,
  CPCasesPageV2,
  CPEvidencePageV2,
  CPExplainablePage,
  CPAISummaryPage,
  CPDownloadReportsPage,
  CPPredictionsPageV2,
  CPReportGenPage,
  CPSearchPage,
  CPSimilarPageV2,
  CPUploadPage,
  CPWorkspacePage,
} from './ClientPortalPages'
import {
  LPAIChatV2,
  LPAIStrategyV2,
  LPAnalyticsV2,
  LPBillingPage,
  LPCalendarPage,
  LPCasesV2,
  LPClientDetailPage,
  LPClientsV2,
  LPDashboardV2,
  LPDocumentsV2,
  LPEvidenceV2,
  LPHearingsV2,
  LPMessagesV2,
  LPPredictionV2,
  LPProfileV2,
  LPReportGenPage,
  LPResearchPage,
  LPSettingsV2,
  LPSimilarV2,
  LPStrategyPage,
  LPTasksPage,
  LPTeamV2,
  LPTimelineV2,
} from './LawyerPortalPages'

type FigmaNavProps = { navigate: (page: string) => void; current?: string }

const PAGES: Record<string, ComponentType<FigmaNavProps>> = {
  'lp-dashboard': LPDashboardV2,
  'lp-clients': LPClientsV2,
  'lp-client-detail': LPClientDetailPage,
  'lp-cases': LPCasesV2,
  'lp-hearings': LPHearingsV2,
  'lp-calendar': LPCalendarPage,
  'lp-tasks': LPTasksPage,
  'lp-documents': LPDocumentsV2,
  'lp-evidence': LPEvidenceV2,
  'lp-research': LPResearchPage,
  'lp-similar': LPSimilarV2,
  'lp-prediction': LPPredictionV2,
  'lp-strategy': LPStrategyPage,
  'lp-timeline': LPTimelineV2,
  'lp-ai-chat': LPAIChatV2,
  'lp-report-gen': LPReportGenPage,
  'lp-team': LPTeamV2,
  'lp-messages': LPMessagesV2,
  'lp-analytics': LPAnalyticsV2,
  'lp-billing': LPBillingPage,
  'lp-profile': LPProfileV2,
  'lp-settings': LPSettingsV2,
  'lp-ai-strategy': LPAIStrategyV2,
  'cp-dashboard': CPDashboardPageV2,
  'cp-cases': CPCasesPageV2,
  'cp-workspace': CPWorkspacePage,
  'cp-upload': CPUploadPage,
  'cp-evidence': CPEvidencePageV2,
  'cp-ai-summary': CPAISummaryPage,
  'cp-similar': CPSimilarPageV2,
  'cp-predictions': CPPredictionsPageV2,
  'cp-explainable': CPExplainablePage,
  'cp-report-gen': CPReportGenPage,
  'cp-downloads': CPDownloadReportsPage,
  'cp-search': CPSearchPage,
  'ap-dashboard': APDashboardV2,
  'ap-users': APUsersV2,
  'ap-lawyers': APLawyersV2,
  'ap-clients': APClientsV2,
  'ap-roles': APRolesV2,
  'ap-ai-model': APAIModelV2,
  'ap-datasets': APDatasetsV2,
  'ap-knowledge': APKnowledgeBasePage,
  'ap-analytics': APAnalyticsV2,
  'ap-audit': APAuditV2,
  'ap-security': APSecurityV2,
  'ap-api': APAPIManagementPage,
  'ap-billing': APBillingV2,
  'ap-support': APSupportPage,
  'ap-cms': APCMSPage,
  'ap-settings': APSettingsV2,
  'ap-backup': APBackupPage,
  'ap-health': APHealthPage,
  'ap-reports': APReportsV2,
}

const DESTINATIONS: Record<string, string> = {
  dashboard: '/dashboard',
  cases: '/cases',
  workspace: '/workspace',
  documents: '/documents',
  evidence: '/evidence',
  prediction: '/prediction',
  'similar-cases': '/similar-cases',
  'ai-chat': '/ai-chat',
  timeline: '/timeline',
  reports: '/reports',
  analytics: '/analytics',
  notifications: '/notifications',
  profile: '/profile',
  settings: '/settings',
  'lp-clients': '/clients',
  'lp-client-detail': '/clients/detail',
  'lp-hearings': '/hearings',
  'lp-calendar': '/calendar',
  'lp-tasks': '/tasks',
  'lp-research': '/research',
  'lp-strategy': '/strategy',
  'lp-report-gen': '/report-generator',
  'lp-billing': '/billing',
  'lp-ai-strategy': '/ai-strategy',
  'lp-messages': '/messages',
  'lp-team': '/team',
  'cp-dashboard': '/client',
  'cp-cases': '/client/cases',
  'cp-search': '/client/search',
  'cp-workspace': '/client/workspace',
  'cp-upload': '/client/upload',
  'cp-evidence': '/client/evidence',
  'cp-ai-summary': '/client/ai-summary',
  'cp-similar': '/client/similar-cases',
  'cp-predictions': '/client/predictions',
  'cp-explainable': '/client/explainable',
  'cp-report-gen': '/client/report-generator',
  'cp-download-reports': '/client/downloads',
  'cp-notifications': '/notifications',
  'cp-profile': '/profile',
  'cp-settings': '/settings',
  'ap-dashboard': '/admin',
  'ap-users': '/admin/users',
  'ap-lawyers': '/admin/lawyers',
  'ap-clients': '/admin/clients',
  'ap-roles': '/admin/roles',
  'ap-ai-model': '/admin/ai-models',
  'ap-datasets': '/admin/datasets',
  'ap-knowledge': '/admin/knowledge',
  'ap-analytics': '/admin/analytics',
  'ap-audit': '/admin/audit',
  'ap-security': '/admin/security',
  'ap-api': '/admin/api',
  'ap-billing': '/admin/billing',
  'ap-support': '/admin/support',
  'ap-cms': '/admin/cms',
  'ap-settings': '/admin/settings',
  'ap-notifications': '/notifications',
  'ap-backup': '/admin/backup',
  'ap-health': '/admin/health',
  'ap-reports': '/admin/reports',
}

export default function FigmaPortalPage({ page }: { page: string }) {
  const navigate = useNavigate()
  const Page = PAGES[page] ?? LPDashboardV2
  const navigateFromFigma = (destination: string) => {
    navigate(DESTINATIONS[destination] ?? `/${destination}`)
  }

  return <Page navigate={navigateFromFigma} current={page} />
}
