create extension if not exists vector with schema extensions;

create table if not exists public.legal_judgment_chunks (
  id bigint generated by default as identity primary key,
  canonical_chunk_id text not null unique,
  source_path text not null,
  source_dataset text not null default 'supabase-storage',
  document_id text not null,
  title text,
  court text,
  jurisdiction text not null default 'Pakistan',
  case_category text,
  case_number text,
  decision_date date,
  language text,
  chunk_type text not null default 'judgment',
  heading text,
  text_content text not null,
  text_preview text not null,
  explicit_outcome_phrase text,
  legal_citations jsonb not null default '[]'::jsonb,
  laws_cited jsonb not null default '[]'::jsonb,
  sections_cited jsonb not null default '[]'::jsonb,
  articles_cited jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1024) not null,
  embedding_model text not null default 'BAAI/bge-m3',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.legal_judgment_chunks enable row level security;
revoke all on public.legal_judgment_chunks from anon, authenticated;
grant select, insert, update on public.legal_judgment_chunks to service_role;
grant usage, select on sequence public.legal_judgment_chunks_id_seq to service_role;

create index if not exists legal_judgment_chunks_embedding_hnsw
  on public.legal_judgment_chunks
  using hnsw (embedding extensions.vector_cosine_ops);
create index if not exists legal_judgment_chunks_category_idx
  on public.legal_judgment_chunks (case_category);
create index if not exists legal_judgment_chunks_court_idx
  on public.legal_judgment_chunks (court);

create or replace function public.match_legal_judgments(
  query_embedding extensions.vector(1024),
  match_count integer default 20,
  match_threshold double precision default 0.2,
  filter_court text default null,
  filter_jurisdiction text default 'Pakistan',
  filter_category text default null,
  require_outcome boolean default false
)
returns table (
  canonical_chunk_id text,
  source_path text,
  source_dataset text,
  document_id text,
  title text,
  court text,
  jurisdiction text,
  case_category text,
  case_number text,
  decision_date date,
  language text,
  chunk_type text,
  heading text,
  text_preview text,
  explicit_outcome_phrase text,
  legal_citations jsonb,
  laws_cited jsonb,
  sections_cited jsonb,
  articles_cited jsonb,
  metadata jsonb,
  similarity double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    c.canonical_chunk_id, c.source_path, c.source_dataset, c.document_id,
    c.title, c.court, c.jurisdiction, c.case_category, c.case_number,
    c.decision_date, c.language, c.chunk_type, c.heading, c.text_preview,
    c.explicit_outcome_phrase, c.legal_citations, c.laws_cited,
    c.sections_cited, c.articles_cited, c.metadata,
    1 - (c.embedding OPERATOR(extensions.<=>) query_embedding) as similarity
  from public.legal_judgment_chunks c
  where (filter_court is null or c.court = filter_court)
    and (filter_jurisdiction is null or c.jurisdiction = filter_jurisdiction)
    and (filter_category is null or c.case_category = filter_category)
    and (not require_outcome or c.explicit_outcome_phrase is not null)
    and 1 - (c.embedding OPERATOR(extensions.<=>) query_embedding) >= match_threshold
  order by c.embedding OPERATOR(extensions.<=>) query_embedding
  limit least(greatest(match_count, 1), 100);
$$;

revoke all on function public.match_legal_judgments(
  extensions.vector, integer, double precision, text, text, text, boolean
) from public, anon, authenticated;
grant execute on function public.match_legal_judgments(
  extensions.vector, integer, double precision, text, text, text, boolean
) to service_role;

create or replace function public.list_legal_storage_objects(
  target_bucket text,
  path_prefix text default 'datasets/raw/',
  page_limit integer default 500,
  page_offset integer default 0
)
returns table (name text, object_size bigint, updated_at timestamptz)
language sql
stable
security invoker
set search_path = ''
as $$
  select o.name, coalesce((o.metadata->>'size')::bigint, 0), o.updated_at
  from storage.objects o
  where o.bucket_id = target_bucket and o.name like path_prefix || '%'
  order by o.name
  limit least(greatest(page_limit, 1), 1000)
  offset greatest(page_offset, 0);
$$;

revoke all on function public.list_legal_storage_objects(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.list_legal_storage_objects(text, text, integer, integer)
  to service_role;
