import { useEffect, useMemo, useState } from 'react'
import { Briefcase, CheckCircle2, FileText, Gavel, ListTodo } from 'lucide-react'
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
import { errorMessage, listCases, listHearings, listLawyerTasks, listMyReports, type Case, type Hearing, type LawyerTask, type ReportSummary } from '../lib/api'
import { Card, KPICard, G } from '../components/design'
import ErrorAlert from '../components/ErrorAlert'

const COLORS = ['#D4AF37', '#8B5CF6', '#3B82F6', '#10B981', '#EF4444', '#F59E0B']
export default function Analytics() {
  const [cases, setCases] = useState<Case[]>([]), [tasks, setTasks] = useState<LawyerTask[]>([]), [hearings, setHearings] = useState<Hearing[]>([]), [reports, setReports] = useState<ReportSummary[]>([])
  const [loading, setLoading] = useState(true), [error, setError] = useState('')
  useEffect(() => { let cancelled = false; Promise.all([listCases(), listLawyerTasks(), listHearings(), listMyReports()]).then(([caseData, taskData, hearingData, reportData]) => { if (!cancelled) { setCases(caseData.items.filter(item => Boolean(item.lawyer_name))); setTasks(taskData); setHearings(hearingData); setReports(reportData) } }).catch(err => { if (!cancelled) setError(errorMessage(err)) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [])
  const active = cases.filter(item => !['Case Complete', 'Closed'].includes(item.status)).length
  const completedHearings = hearings.filter(item => item.status === 'Completed').length
  const openTasks = tasks.filter(item => item.status !== 'Done').length
  const distribution = useMemo(() => { const counts = new Map<string, number>(); cases.forEach(item => counts.set(item.case_type, (counts.get(item.case_type) ?? 0) + 1)); return Array.from(counts, ([name, value], index) => ({ name, value, color: COLORS[index % COLORS.length] })) }, [cases])
  const statuses = useMemo(() => { const counts = new Map<string, number>(); cases.forEach(item => counts.set(item.status, (counts.get(item.status) ?? 0) + 1)); return Array.from(counts, ([name, value]) => ({ name, value })) }, [cases])
  return <div className="h-full overflow-auto p-6 space-y-6"><header><h1 className="text-2xl font-bold">Practice Analytics</h1><p className="mt-1 text-sm text-muted-foreground">Live operational metrics from your assigned cases, tasks, hearings, and reports.</p></header>{error ? <ErrorAlert message={error}/> : null}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KPICard icon={<Briefcase size={18}/>} label="Assigned cases" value={loading ? '…' : String(cases.length)} sub={`${active} active`} color={G}/><KPICard icon={<CheckCircle2 size={18}/>} label="Completed cases" value={loading ? '…' : String(cases.length - active)} sub="Saved case statuses" color="#10B981"/><KPICard icon={<ListTodo size={18}/>} label="Open tasks" value={loading ? '…' : String(openTasks)} sub={`${tasks.filter(item => item.status === 'Done').length} completed`} color="#3B82F6"/><KPICard icon={<Gavel size={18}/>} label="Hearings" value={loading ? '…' : String(hearings.length)} sub={`${completedHearings} completed`} color="#8B5CF6"/><KPICard icon={<FileText size={18}/>} label="Reports" value={loading ? '…' : String(reports.length)} sub="Generated records" color="#F59E0B"/></div><div className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="font-bold">Case types</h2>{distribution.length ? <><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={distribution} dataKey="value" innerRadius={55} outerRadius={85} paddingAngle={3}>{distribution.map(item => <Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="grid grid-cols-2 gap-2">{distribution.map(item => <div key={item.name} className="flex items-center gap-2 text-xs"><i className="h-2.5 w-2.5 rounded-full" style={{ background: item.color }}/><span className="truncate text-muted-foreground">{item.name}</span><b className="ml-auto">{item.value}</b></div>)}</div></> : <p className="py-16 text-center text-sm text-muted-foreground">No assigned cases yet.</p>}</Card><Card className="p-5"><h2 className="font-bold">Case status</h2><div className="mt-5 space-y-3">{statuses.map(item => { const percentage = cases.length ? Math.round(item.value / cases.length * 100) : 0; return <div key={item.name}><div className="mb-1 flex justify-between text-xs"><span>{item.name}</span><span className="text-muted-foreground">{item.value} · {percentage}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full" style={{ width: `${percentage}%`, background: G }}/></div></div>})}{!statuses.length ? <p className="py-16 text-center text-sm text-muted-foreground">No status data yet.</p> : null}</div></Card></div><p className="text-center text-xs text-muted-foreground">No win rate or revenue is shown because wukaLAW has no verified outcome or time-billing ledger for these cases.</p></div>
}
