import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { MessageSquare, Send } from 'lucide-react'
import { errorMessage, getStoredUser, listCaseMessages, listCases, sendCaseMessage, type Case, type CaseMessage } from '../lib/api'
import { Card, G } from '../components/design'
import ErrorAlert from '../components/ErrorAlert'

export default function LawyerMessages() {
  const user = getStoredUser(), [cases, setCases] = useState<Case[]>([]), [caseId, setCaseId] = useState(''), [messages, setMessages] = useState<CaseMessage[]>([]), [body, setBody] = useState('')
  const [loading, setLoading] = useState(true), [sending, setSending] = useState(false), [error, setError] = useState('')
  useEffect(() => { listCases().then(result => setCases(result.items.filter(item => Boolean(item.lawyer_name && item.client_id)))).catch(err => setError(errorMessage(err))).finally(() => setLoading(false)) }, [])
  const choose = async (value: string) => { setCaseId(value); setMessages([]); if (!value) return; try { setMessages(await listCaseMessages(Number(value))); setError('') } catch (err) { setError(errorMessage(err)) } }
  const send = async (event: FormEvent) => { event.preventDefault(); if (!caseId || !body.trim()) return; setSending(true); try { const message = await sendCaseMessage(Number(caseId), body.trim()); setMessages(current => [...current, message]); setBody(''); setError('') } catch (err) { setError(errorMessage(err)) } finally { setSending(false) } }
  const isClient = user?.role === 'client'
  return <div className="h-full overflow-auto p-6 space-y-5"><header><h1 className="text-2xl font-bold">{isClient ? 'Messages with your lawyer' : 'Client Messages'}</h1><p className="mt-1 text-sm text-muted-foreground">{isClient ? 'Read and reply to updates from the lawyer assigned to your case.' : 'Case-linked communication between you and the assigned client.'}</p></header>{error ? <ErrorAlert message={error}/> : null}<label className="block text-xs font-semibold text-muted-foreground">Conversation<select aria-label="Message case" disabled={loading} value={caseId} onChange={event => void choose(event.target.value)} className="mt-1 block w-full rounded-xl border border-border bg-card px-3 py-2.5 text-sm"><option value="">Choose a case…</option>{cases.map(item => <option key={item.id} value={item.id}>{item.case_number} — {isClient ? item.title : (item.client_name ?? item.title)}</option>)}</select></label><Card className="flex min-h-[480px] flex-col overflow-hidden"><div className="flex-1 space-y-3 overflow-auto p-5">{caseId && messages.length ? messages.map(message => { const mine = message.sender_id === user?.id; return <div key={message.id} className={`flex ${mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 ${mine ? 'bg-[#D4AF37]/15' : 'bg-background'}`}><p className="text-xs font-semibold" style={{ color: mine ? G : undefined }}>{mine ? 'You' : message.sender_name}</p><p className="mt-1 whitespace-pre-wrap text-sm">{message.body}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(message.created_at).toLocaleString()}</p></div></div> }) : <div className="grid h-full min-h-[350px] place-items-center text-center"><div><MessageSquare size={30} className="mx-auto text-muted-foreground"/><p className="mt-3 text-sm font-medium">{caseId ? 'No messages yet' : 'Choose a case conversation'}</p><p className="mt-1 text-xs text-muted-foreground">Messages are saved against the selected case.</p></div></div>}</div><form onSubmit={send} className="flex gap-2 border-t border-border p-4"><textarea aria-label="Message" disabled={!caseId} rows={2} value={body} onChange={event => setBody(event.target.value)} className="flex-1 resize-none rounded-xl border border-border bg-background p-3 text-sm" placeholder="Write a case update or request…"/><button aria-label="Send message" disabled={!caseId || !body.trim() || sending} className="self-end rounded-xl p-3 text-black disabled:opacity-50" style={{ background: G }}><Send size={17}/></button></form></Card></div>
}
