import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Brain, Calendar, FileText, FolderOpen, Gavel, ListTodo } from 'lucide-react'
import { errorMessage, getCaseTimeline, listCaseDocuments, listCases, listHearings, listLawyerTasks, type Case, type DocumentMeta, type Hearing, type LawyerTask, type TimelineEvent } from '../lib/api'

type Tab='overview'|'documents'|'timeline'|'work'
export default function LawyerWorkspace(){
 const navigate=useNavigate(),[cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState<number|null>(null),[docs,setDocs]=useState<DocumentMeta[]>([]),[timeline,setTimeline]=useState<TimelineEvent[]>([]),[tasks,setTasks]=useState<LawyerTask[]>([]),[hearings,setHearings]=useState<Hearing[]>([]),[tab,setTab]=useState<Tab>('overview'),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{listCases().then(r=>{setCases(r.items);if(r.items[0])setSelected(r.items[0].id)}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[])
 useEffect(()=>{if(!selected)return;setLoading(true);Promise.all([listCaseDocuments(selected),getCaseTimeline(selected),listLawyerTasks(),listHearings()]).then(([d,t,allTasks,allHearings])=>{setDocs(d.items);setTimeline(t.events);setTasks(allTasks.filter(x=>x.case_id===selected));setHearings(allHearings.filter(x=>x.case_id===selected));setError('')}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[selected])
 const item=cases.find(c=>c.id===selected)
 return <div className="h-full overflow-hidden flex">
  <aside className="w-72 shrink-0 border-r border-border bg-card/50 p-3 overflow-auto"><h1 className="font-bold text-lg px-2 py-3">Case Workspace</h1>{cases.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full text-left rounded-lg p-3 mb-2 border ${selected===c.id?'border-[#D4AF37]/50 bg-[#D4AF37]/10':'border-transparent hover:bg-white/5'}`}><p className="text-xs text-[#D4AF37]">{c.case_number}</p><p className="font-semibold text-sm mt-1 truncate">{c.title}</p><p className="text-xs text-muted-foreground mt-1">{c.status} · {c.num_documents} document(s)</p></button>)}{!cases.length&&!loading&&<p className="text-sm text-muted-foreground p-3">Create or claim a case to use the workspace.</p>}</aside>
  <main className="flex-1 overflow-auto p-6">{error&&<div className="mb-4 rounded-lg bg-red-500/10 border border-red-500/30 p-3 text-sm text-red-300">{error}</div>}{!item?<div className="h-full grid place-items-center text-muted-foreground"><FolderOpen size={38}/></div>:<>
   <header className="flex flex-wrap gap-4 justify-between"><div><p className="text-sm text-[#D4AF37]">{item.case_number}</p><h2 className="text-2xl font-bold">{item.title}</h2><p className="text-sm text-muted-foreground mt-1">{item.case_type} · {item.status} · {item.priority} priority</p></div><div className="flex gap-2"><button onClick={()=>navigate(`/cases/${item.id}`)} className="border border-border rounded-lg px-3 py-2 text-sm">Edit case</button><button onClick={()=>navigate('/ai-chat',{state:{caseId:item.id}})} className="bg-[#D4AF37] text-black rounded-lg px-3 py-2 text-sm font-semibold flex gap-2 items-center"><Brain size={15}/>Ask AI</button></div></header>
   <nav className="flex gap-1 border-b border-border mt-6">{(['overview','documents','timeline','work'] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={`capitalize px-4 py-3 text-sm border-b-2 ${tab===x?'border-[#D4AF37] text-foreground':'border-transparent text-muted-foreground'}`}>{x}</button>)}</nav>
   {loading?<p className="py-10 text-muted-foreground">Loading case workspace…</p>:<div className="py-5">
    {tab==='overview'&&<div className="space-y-4"><div className="grid md:grid-cols-4 gap-3">{[[FileText,'Documents',docs.length],[Calendar,'Dated events',timeline.length],[ListTodo,'Open tasks',tasks.filter(t=>t.status!=='Done').length],[Gavel,'Hearings',hearings.length]].map(([Icon,label,value])=>{const I=Icon as typeof FileText;return <div key={String(label)} className="rounded-xl border border-border bg-card p-4"><I size={17} className="text-[#D4AF37]"/><p className="text-2xl font-bold mt-2">{String(value)}</p><p className="text-xs text-muted-foreground">{String(label)}</p></div>})}</div><section className="rounded-xl border border-border bg-card p-5"><h3 className="font-bold mb-2">Case description</h3><p className="text-sm text-muted-foreground whitespace-pre-wrap">{item.description||'No case description has been recorded yet.'}</p></section><section className="rounded-xl border border-border bg-card p-5"><h3 className="font-bold mb-2">Next deadline</h3><p className="text-sm">{item.deadline?new Date(item.deadline).toLocaleDateString():'No deadline recorded.'}</p></section></div>}
    {tab==='documents'&&<div className="grid md:grid-cols-2 gap-3">{docs.map(d=><button key={d.id} onClick={()=>navigate(`/documents/${d.id}`)} className="rounded-xl border border-border bg-card p-4 text-left"><FileText size={17} className="text-[#D4AF37]"/><h3 className="font-semibold mt-2">{d.title}</h3><p className="text-xs text-muted-foreground mt-1">{d.filename} · {d.num_chunks} searchable chunk(s)</p></button>)}{!docs.length&&<p className="text-muted-foreground">No documents linked to this case.</p>}</div>}
    {tab==='timeline'&&<div className="space-y-3">{timeline.map((e,i)=><div key={`${e.document_id}-${i}`} className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-[#D4AF37]">{e.date_text}</p><p className="text-sm mt-1">{e.text}</p><button onClick={()=>navigate(`/documents/${e.document_id}`)} className="text-xs text-muted-foreground mt-2">Source: {e.document_title}</button></div>)}{!timeline.length&&<p className="text-muted-foreground">No dated events extracted from the linked documents.</p>}</div>}
    {tab==='work'&&<div className="grid lg:grid-cols-2 gap-4"><section><div className="flex justify-between mb-3"><h3 className="font-bold">Tasks</h3><button onClick={()=>navigate('/tasks')} className="text-xs text-[#D4AF37]">Open board</button></div>{tasks.map(t=><div key={t.id} className="rounded-lg border border-border bg-card p-3 mb-2"><p className="font-semibold text-sm">{t.title}</p><p className="text-xs text-muted-foreground mt-1">{t.status} · {t.priority}{t.due_at&&` · due ${new Date(t.due_at).toLocaleDateString()}`}</p></div>)}</section><section><div className="flex justify-between mb-3"><h3 className="font-bold">Hearings</h3><button onClick={()=>navigate('/hearings')} className="text-xs text-[#D4AF37]">Manage hearings</button></div>{hearings.map(h=><div key={h.id} className="rounded-lg border border-border bg-card p-3 mb-2"><p className="font-semibold text-sm">{h.title}</p><p className="text-xs text-muted-foreground mt-1">{new Date(h.scheduled_at).toLocaleString()} · {h.court}</p></div>)}</section></div>}
   </div>}
  </>}</main>
 </div>
}
