import { useEffect, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { createLawyerTask, deleteLawyerTask, errorMessage, listCases, listLawyerTasks, updateLawyerTask, type Case, type LawyerTask } from '../lib/api'

const columns: LawyerTask['status'][] = ['To Do','In Progress','Review','Done']
const field='rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground'
export default function LawyerTasks(){
 const [tasks,setTasks]=useState<LawyerTask[]>([]),[cases,setCases]=useState<Case[]>([]),[open,setOpen]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({title:'',case_id:'',priority:'Medium' as LawyerTask['priority'],due_at:'',notes:''})
 const load=async()=>{try{const[t,c]=await Promise.all([listLawyerTasks(),listCases()]);setTasks(t);setCases(c.items);setError('')}catch(e){setError(errorMessage(e))}}
 useEffect(()=>{void load()},[])
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{await createLawyerTask({title:form.title,case_id:form.case_id?Number(form.case_id):null,status:'To Do',priority:form.priority,due_at:form.due_at?new Date(form.due_at).toISOString():null,notes:form.notes});setOpen(false);setForm({...form,title:'',notes:''});await load()}catch(err){setError(errorMessage(err))}}
 return <div className="p-6 h-full overflow-auto"><div className="flex justify-between gap-3 flex-wrap mb-5"><div><h1 className="text-2xl font-bold">Task Board</h1><p className="text-sm text-muted-foreground">Move real work through your case workflow.</p></div><button onClick={()=>setOpen(!open)} className="bg-[#D4AF37] text-black font-semibold rounded-lg px-4 py-2 flex gap-2 items-center"><Plus size={15}/>Add task</button></div>
 {error&&<div className="mb-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
 {open&&<form onSubmit={save} className="mb-5 grid md:grid-cols-5 gap-3 rounded-xl border border-border bg-card p-4"><input required className={`${field} md:col-span-2`} placeholder="What needs to be done?" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className={field} value={form.case_id} onChange={e=>setForm({...form,case_id:e.target.value})}><option value="">No case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number} — {c.title}</option>)}</select><select className={field} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as LawyerTask['priority']})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select><input className={field} type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/><textarea className={`${field} md:col-span-4`} placeholder="Instructions or checklist" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="bg-[#D4AF37] rounded-lg text-black font-semibold">Create</button></form>}
 <div className="grid xl:grid-cols-4 md:grid-cols-2 gap-4">{columns.map((col,idx)=><section key={col} className="rounded-xl border border-border bg-card/50 p-3 min-h-64"><div className="flex justify-between mb-3"><h2 className="font-semibold">{col}</h2><span className="text-xs rounded-full bg-white/10 px-2 py-1">{tasks.filter(t=>t.status===col).length}</span></div><div className="space-y-3">{tasks.filter(t=>t.status===col).map(t=><article key={t.id} className="rounded-lg border border-border bg-card p-3"><div className="flex gap-2"><h3 className="text-sm font-semibold flex-1">{t.title}</h3><button aria-label="Delete task" onClick={async()=>{await deleteLawyerTask(t.id);await load()}}><Trash2 size={14} className="text-muted-foreground"/></button></div><p className="text-xs text-[#D4AF37] mt-1">{t.case_number||'General'} {t.case_title&&`· ${t.case_title}`}</p>{t.notes&&<p className="text-xs text-muted-foreground mt-2 line-clamp-3">{t.notes}</p>}<div className="mt-3 flex items-center justify-between"><span className="text-[10px] border border-border rounded px-2 py-1">{t.priority}</span><span className="text-[10px] text-muted-foreground">{t.due_at?new Date(t.due_at).toLocaleDateString():'No due date'}</span></div><div className="flex gap-1 mt-3">{idx>0&&<button className="text-[10px] border border-border rounded px-2 py-1" onClick={async()=>{await updateLawyerTask(t.id,{status:columns[idx-1]});await load()}}>← Back</button>}{idx<3&&<button className="text-[10px] bg-[#D4AF37] text-black rounded px-2 py-1 ml-auto" onClick={async()=>{await updateLawyerTask(t.id,{status:columns[idx+1]});await load()}}>Move →</button>}</div></article>)}</div></section>)}</div>
 </div>
}
