import { useEffect, useState } from 'react'
import { Save, ShieldCheck } from 'lucide-react'
import { errorMessage, getCaseStrategy, listCases, saveCaseStrategy, type Case, type CaseStrategy } from '../lib/api'
import { Card, G } from '../components/design'
import ErrorAlert from '../components/ErrorAlert'

const empty = { objective: '', case_theory: '', strengths: [] as string[], risks: [] as string[], next_actions: [] as string[] }
const lines = (value: string) => value.split('\n').map(item => item.trim()).filter(Boolean)
export default function LawyerStrategy() {
  const [cases, setCases] = useState<Case[]>([]), [caseId, setCaseId] = useState(''), [form, setForm] = useState(empty)
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false), [error, setError] = useState('')
  useEffect(() => { listCases().then(result => setCases(result.items.filter(item => Boolean(item.lawyer_name)))).catch(err => setError(errorMessage(err))).finally(() => setLoading(false)) }, [])
  const choose = async (value: string) => { setCaseId(value); setSaved(false); if (!value) { setForm(empty); return } try { const strategy = await getCaseStrategy(Number(value)); setForm({ objective: strategy.objective, case_theory: strategy.case_theory, strengths: strategy.strengths, risks: strategy.risks, next_actions: strategy.next_actions }); setError('') } catch (err) { setError(errorMessage(err)) } }
  const save = async () => { if (!caseId) return; setSaving(true); try { const strategy: CaseStrategy = await saveCaseStrategy(Number(caseId), form); setForm({ objective: strategy.objective, case_theory: strategy.case_theory, strengths: strategy.strengths, risks: strategy.risks, next_actions: strategy.next_actions }); setSaved(true); setError('') } catch (err) { setError(errorMessage(err)) } finally { setSaving(false) } }
  return <div className="h-full overflow-auto p-6 space-y-5"><header><h1 className="text-2xl font-bold">Case Strategy Builder</h1><p className="mt-1 text-sm text-muted-foreground">Build and save a separate working strategy for each assigned case.</p></header>{error ? <ErrorAlert message={error}/> : null}<Card className="p-5"><label className="text-xs font-semibold text-muted-foreground">Case<select aria-label="Strategy case" disabled={loading} value={caseId} onChange={event => void choose(event.target.value)} className="mt-1 block w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm"><option value="">Choose an assigned case…</option>{cases.map(item => <option key={item.id} value={item.id}>{item.case_number} — {item.title}</option>)}</select></label></Card>{caseId ? <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5 lg:col-span-2"><label className="text-xs font-semibold text-muted-foreground">Primary objective<textarea rows={3} value={form.objective} onChange={event => setForm({ ...form, objective: event.target.value })} className="mt-2 w-full rounded-xl border border-border bg-background p-3 text-sm" placeholder="What result is the client asking you to achieve?"/></label></Card><Card className="p-5 lg:col-span-2"><label className="text-xs font-semibold text-muted-foreground">Case theory<textarea rows={5} value={form.case_theory} onChange={event => setForm({ ...form, case_theory: event.target.value })} className="mt-2 w-full rounded-xl border border-border bg-background p-3 text-sm" placeholder="Your concise factual and legal theory, based on verified material."/></label></Card>{([['strengths','Strengths','One verified strength per line'],['risks','Risks and weaknesses','One risk or opposing argument per line'],['next_actions','Next actions','One concrete action per line']] as const).map(([key, title, placeholder]) => <Card key={key} className="p-5"><label className="text-xs font-semibold text-muted-foreground">{title}<textarea rows={7} value={form[key].join('\n')} onChange={event => setForm({ ...form, [key]: lines(event.target.value) })} className="mt-2 w-full rounded-xl border border-border bg-background p-3 text-sm" placeholder={placeholder}/></label></Card>)}</div> : <Card className="p-10 text-center"><ShieldCheck size={28} className="mx-auto text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">Select a case to open its strategy workspace.</p></Card>}{caseId ? <div className="flex items-center justify-end gap-3">{saved ? <span className="text-xs text-emerald-400">Strategy saved</span> : null}<button disabled={saving} onClick={() => void save()} className="flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-bold text-black disabled:opacity-50" style={{ background: G }}><Save size={15}/>{saving ? 'Saving…' : 'Save strategy'}</button></div> : null}</div>
}
