import { useEffect, useState } from 'react'
import { BookOpen, Search, Trash2 } from 'lucide-react'
import { askCaseQuestion, createResearchLog, deleteResearchLog, errorMessage, listCases, listResearchLogs, type AskResponse, type Case, type ResearchLog } from '../lib/api'
const field='w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground'
export default function LawyerResearch(){
 const [cases,setCases]=useState<Case[]>([]),[logs,setLogs]=useState<ResearchLog[]>([]),[caseId,setCaseId]=useState(''),[query,setQuery]=useState(''),[result,setResult]=useState<AskResponse|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const load=async()=>{try{const[c,l]=await Promise.all([listCases(),listResearchLogs()]);setCases(c.items);setLogs(l);setError('')}catch(e){setError(errorMessage(e))}}
 useEffect(()=>{void load()},[])
 const run=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const r=await askCaseQuestion(query,caseId?Number(caseId):undefined);setResult(r);await createResearchLog({case_id:caseId?Number(caseId):null,query,notes:r.answer,results:r.sources.map(s=>({...s}))});await load()}catch(err){setError(errorMessage(err))}finally{setLoading(false)}}
 return <div className="p-6 space-y-5 overflow-auto h-full"><div><h1 className="text-2xl font-bold">AI Legal Research</h1><p className="text-sm text-muted-foreground">Research against the selected case record and save the work to its research log.</p></div>
 <form onSubmit={run} className="rounded-xl border border-border bg-card p-5 space-y-3"><select className={field} value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">General research</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number} — {c.title}</option>)}</select><textarea required minLength={3} rows={4} className={field} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask a focused legal question, e.g. What evidence is needed for recovery of unpaid dower under Pakistani family law?"/><button disabled={loading} className="rounded-lg bg-[#D4AF37] px-4 py-2 text-black font-semibold flex items-center gap-2 disabled:opacity-50"><Search size={15}/>{loading?'Researching…':'Run research'}</button></form>
 {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{error}</div>}
 {result&&<section className="rounded-xl border border-[#D4AF37]/30 bg-card p-5"><div className="flex items-center gap-2 mb-3"><BookOpen size={17} className="text-[#D4AF37]"/><h2 className="font-bold">Research answer</h2><span className="ml-auto text-xs text-muted-foreground">{result.confidence.level} confidence</span></div><div className="text-sm whitespace-pre-wrap leading-6">{result.answer}</div>{result.sources.length>0&&<div className="mt-4"><h3 className="text-xs font-bold uppercase text-muted-foreground mb-2">Sources used</h3>{result.sources.map((s,i)=><div key={`${s.document_id}-${i}`} className="border-t border-border py-2 text-xs"><strong>{s.document_title}</strong><p className="text-muted-foreground line-clamp-2">{s.text}</p></div>)}</div>}</section>}
 <section><h2 className="font-bold mb-3">Research log</h2><div className="space-y-3">{logs.map(l=><article key={l.id} className="rounded-xl border border-border bg-card p-4"><div className="flex gap-3"><div className="flex-1"><p className="text-xs text-[#D4AF37]">{l.case_number||'General research'} {l.case_title&&`· ${l.case_title}`}</p><h3 className="font-semibold mt-1">{l.query}</h3><p className="mt-2 text-sm text-muted-foreground whitespace-pre-wrap line-clamp-4">{l.notes}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(l.created_at).toLocaleString()} · {l.results.length} saved source(s)</p></div><button aria-label="Delete research log" onClick={async()=>{await deleteResearchLog(l.id);await load()}}><Trash2 size={15}/></button></div></article>)}{!logs.length&&<p className="rounded-xl border border-dashed border-border p-8 text-center text-muted-foreground">No saved research yet.</p>}</div></section>
 </div>
}
