import { useEffect, useState } from 'react'
import { Gavel, Plus, Trash2 } from 'lucide-react'
import { createHearing, deleteHearing, errorMessage, listCases, listHearings, updateHearing, type Case, type Hearing } from '../lib/api'
const field='w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground'
export default function LawyerHearings(){
 const [items,setItems]=useState<Hearing[]>([]),[cases,setCases]=useState<Case[]>([]),[open,setOpen]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({case_id:'',title:'',scheduled_at:'',court:'',judge:'',hearing_type:'Hearing',preparation_notes:''})
 const load=async()=>{try{const[h,c]=await Promise.all([listHearings(),listCases()]);setItems(h);setCases(c.items);setError('')}catch(e){setError(errorMessage(e))}}
 useEffect(()=>{void load()},[])
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{await createHearing({...form,case_id:Number(form.case_id),scheduled_at:new Date(form.scheduled_at).toISOString(),status:'Scheduled',outcome:''});setOpen(false);setForm({...form,title:'',court:'',judge:'',preparation_notes:''});await load()}catch(err){setError(errorMessage(err))}}
 const now=Date.now(), upcoming=items.filter(x=>new Date(x.scheduled_at).getTime()>=now&&x.status==='Scheduled'), past=items.filter(x=>!upcoming.includes(x))
 return <div className="p-6 space-y-5 overflow-auto h-full"><div className="flex justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-bold">Hearings</h1><p className="text-sm text-muted-foreground">Schedule appearances, prepare notes, and record outcomes.</p></div><button onClick={()=>setOpen(!open)} className="bg-[#D4AF37] text-black rounded-lg px-4 py-2 font-semibold flex gap-2 items-center"><Plus size={15}/>Add hearing</button></div>
 {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{error}</div>}
 {open&&<form onSubmit={save} className="grid md:grid-cols-3 gap-3 rounded-xl border border-border bg-card p-4"><select required className={field} value={form.case_id} onChange={e=>setForm({...form,case_id:e.target.value})}><option value="">Choose case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number} — {c.title}</option>)}</select><input required className={field} placeholder="Hearing title / purpose" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required type="datetime-local" className={field} value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/><input required className={field} placeholder="Court" value={form.court} onChange={e=>setForm({...form,court:e.target.value})}/><input className={field} placeholder="Judge (if known)" value={form.judge} onChange={e=>setForm({...form,judge:e.target.value})}/><select className={field} value={form.hearing_type} onChange={e=>setForm({...form,hearing_type:e.target.value})}>{['Hearing','Evidence','Arguments','Reconciliation','Order','Compliance'].map(x=><option key={x}>{x}</option>)}</select><textarea className={`${field} md:col-span-2`} placeholder="What must be prepared?" value={form.preparation_notes} onChange={e=>setForm({...form,preparation_notes:e.target.value})}/><button className="bg-[#D4AF37] text-black font-semibold rounded-lg">Save hearing</button></form>}
 {[['Upcoming',upcoming],['History',past]].map(([label,list])=><section key={label as string}><h2 className="font-bold mb-3">{label as string} <span className="text-muted-foreground text-sm">({(list as Hearing[]).length})</span></h2><div className="grid lg:grid-cols-2 gap-4">{(list as Hearing[]).map(h=><article key={h.id} className="rounded-xl border border-border bg-card p-4"><div className="flex gap-3"><div className="rounded-lg bg-purple-500/15 p-2 h-fit"><Gavel size={18} className="text-purple-300"/></div><div className="flex-1"><div className="flex justify-between gap-3"><div><p className="text-xs text-[#D4AF37]">{h.case_number} · {h.case_title}</p><h3 className="font-bold mt-1">{h.title}</h3></div><button aria-label="Delete hearing" onClick={async()=>{await deleteHearing(h.id);await load()}}><Trash2 size={15}/></button></div><p className="text-sm mt-2">{new Date(h.scheduled_at).toLocaleString()}</p><p className="text-xs text-muted-foreground mt-1">{h.court}{h.judge&&` · ${h.judge}`} · {h.hearing_type}</p>{h.preparation_notes&&<div className="mt-3 rounded-lg bg-background p-3 text-xs"><strong>Preparation:</strong> {h.preparation_notes}</div>}<div className="mt-3 flex flex-wrap gap-2">{(['Scheduled','Completed','Adjourned','Cancelled'] as Hearing['status'][]).map(s=><button key={s} onClick={async()=>{await updateHearing(h.id,{status:s});await load()}} className={`rounded px-2 py-1 text-[10px] border ${h.status===s?'bg-[#D4AF37] text-black border-[#D4AF37]':'border-border text-muted-foreground'}`}>{s}</button>)}</div></div></div></article>)}</div>{!(list as Hearing[]).length&&<p className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No {String(label).toLowerCase()} hearings.</p>}</section>)}
 </div>
}
