import { useEffect, useState } from 'react'
import { Download, FilePlus2, FileText, Loader2, X } from 'lucide-react'
import { errorMessage, generateReport, getReport, listCases, listMyReports, type Case, type ReportDetail, type ReportSummary } from '../lib/api'
import { Card, G } from '../components/design'
import ErrorAlert from '../components/ErrorAlert'

export default function Reports({ generatorOnly = false }: { generatorOnly?: boolean }) {
  const [cases, setCases] = useState<Case[]>([]), [reports, setReports] = useState<ReportSummary[]>([])
  const [caseId, setCaseId] = useState(''), [detail, setDetail] = useState<ReportDetail | null>(null)
  const [loading, setLoading] = useState(true), [generating, setGenerating] = useState(false), [error, setError] = useState('')
  const load = async () => { try { const [caseResult, reportResult] = await Promise.all([listCases(), listMyReports()]); const owned = caseResult.items.filter(item => Boolean(item.lawyer_name)); setCases(owned); setReports(reportResult); setError('') } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const generate = async () => { if (!caseId) return; setGenerating(true); try { const created = await generateReport(Number(caseId)); setDetail(created); await load() } catch (err) { setError(errorMessage(err)) } finally { setGenerating(false) } }
  const open = async (id: number) => { try { setDetail(await getReport(id)) } catch (err) { setError(errorMessage(err)) } }
  const download = (report: ReportDetail) => { const blob = new Blob([report.content], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${report.title.replace(/[^a-z0-9]+/gi, '_')}.txt`; anchor.click(); URL.revokeObjectURL(url) }
  return <div className="h-full overflow-auto p-6 space-y-6">
    <header><h1 className="text-2xl font-bold">{generatorOnly ? 'Report Generator' : 'Reports'}</h1><p className="mt-1 text-sm text-muted-foreground">Generate and download reports from saved case data and documents.</p></header>
    {error ? <ErrorAlert message={error}/> : null}
    <Card className="p-5"><div className="flex items-center gap-2"><FilePlus2 size={18} style={{ color: G }}/><h2 className="font-bold">Generate case summary</h2></div><p className="mt-1 text-xs text-muted-foreground">Choose one assigned case. The report includes its current details and document summaries.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="flex-1 text-xs font-semibold text-muted-foreground">Case<select aria-label="Report case" value={caseId} onChange={event => setCaseId(event.target.value)} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm"><option value="">Choose a case…</option>{cases.map(item => <option key={item.id} value={item.id}>{item.case_number} — {item.title}</option>)}</select></label><button disabled={!caseId || generating} onClick={() => void generate()} className="self-end rounded-xl px-5 py-2.5 text-sm font-bold text-black disabled:opacity-50" style={{ background: G }}>{generating ? <span className="flex items-center gap-2"><Loader2 className="animate-spin" size={15}/>Generating…</span> : 'Generate report'}</button></div></Card>
    {!generatorOnly ? <section><h2 className="mb-3 font-bold">Generated reports</h2>{loading ? <p className="text-sm text-muted-foreground">Loading reports…</p> : reports.length ? <div className="space-y-2">{reports.map(report => <button key={report.id} onClick={() => void open(report.id)} className="flex w-full items-center gap-3 rounded-xl border border-border bg-card p-4 text-left hover:border-[#D4AF37]/30"><FileText size={18} className="text-red-400"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{report.title}</p><p className="text-xs text-muted-foreground">{report.case_number} · {new Date(report.created_at).toLocaleString()}</p></div><span className="text-xs" style={{ color: G }}>Open</span></button>)}</div> : <Card className="p-8 text-center text-sm text-muted-foreground">No reports generated yet.</Card>}</section> : null}
    {detail ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><Card className="max-h-[85vh] w-full max-w-3xl overflow-auto p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{detail.title}</h2><p className="text-xs text-muted-foreground">{detail.case_number} · {new Date(detail.created_at).toLocaleString()}</p></div><button aria-label="Close report" onClick={() => setDetail(null)}><X size={18}/></button></div><pre className="mt-5 whitespace-pre-wrap rounded-xl bg-background p-4 text-sm leading-relaxed">{detail.content}</pre><div className="mt-4 flex justify-end"><button onClick={() => download(detail)} className="flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm"><Download size={15}/>Download .txt</button></div></Card></div> : null}
  </div>
}
